---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evalsi-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - evals.si
  resources:
  - evalruns
  - evaluators
  - onlineevalpolicies
  - sandboxclasses
  - tracesources
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - evals.si
  resources:
  - evalruns/finalizers
  - evalruns/status
  - evaluators/status
  - onlineevalpolicies/finalizers
  - onlineevalpolicies/status
  - sandboxclasses/status
  - tracesources/finalizers
  - tracesources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
